'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property txt_IP() As String
            Get
                Return CType(Me("txt_IP"), String)
            End Get
            Set
                Me("txt_IP") = value
            End Set
        End Property


        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property txt_noidung() As String
            Get
                Return CType(Me("txt_noidung"),String)
            End Get
            Set
                Me("txt_noidung") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property code_detail() As String
            Get
                Return CType(Me("code_detail"),String)
            End Get
            Set
                Me("code_detail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property h1a() As String
            Get
                Return CType(Me("h1a"),String)
            End Get
            Set
                Me("h1a") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property b_h1() As String
            Get
                Return CType(Me("b_h1"),String)
            End Get
            Set
                Me("b_h1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property b_m1() As String
            Get
                Return CType(Me("b_m1"),String)
            End Get
            Set
                Me("b_m1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property e_h1() As String
            Get
                Return CType(Me("e_h1"),String)
            End Get
            Set
                Me("e_h1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property e_m1() As String
            Get
                Return CType(Me("e_m1"),String)
            End Get
            Set
                Me("e_m1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property b_h2() As String
            Get
                Return CType(Me("b_h2"),String)
            End Get
            Set
                Me("b_h2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property b_m2() As String
            Get
                Return CType(Me("b_m2"),String)
            End Get
            Set
                Me("b_m2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property e_h2() As String
            Get
                Return CType(Me("e_h2"),String)
            End Get
            Set
                Me("e_h2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property e_m2() As String
            Get
                Return CType(Me("e_m2"),String)
            End Get
            Set
                Me("e_m2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property matrix8010() As String
            Get
                Return CType(Me("matrix8010"),String)
            End Get
            Set
                Me("matrix8010") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property matrix8011() As String
            Get
                Return CType(Me("matrix8011"),String)
            End Get
            Set
                Me("matrix8011") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property matrix90() As String
            Get
                Return CType(Me("matrix90"),String)
            End Get
            Set
                Me("matrix90") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property matrix91() As String
            Get
                Return CType(Me("matrix91"),String)
            End Get
            Set
                Me("matrix91") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property matrix92() As String
            Get
                Return CType(Me("matrix92"),String)
            End Get
            Set
                Me("matrix92") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property matrix93() As String
            Get
                Return CType(Me("matrix93"),String)
            End Get
            Set
                Me("matrix93") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property matrix94() As String
            Get
                Return CType(Me("matrix94"),String)
            End Get
            Set
                Me("matrix94") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property matrix95() As String
            Get
                Return CType(Me("matrix95"), String)
            End Get
            Set
                Me("matrix95") = value
            End Set
        End Property
        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property matrix96() As String
            Get
                Return CType(Me("matrix96"), String)
            End Get
            Set
                Me("matrix96") = Value
            End Set
        End Property
        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property matrix97() As String
            Get
                Return CType(Me("matrix97"), String)
            End Get
            Set
                Me("matrix97") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property qrcode90() As String
            Get
                Return CType(Me("qrcode90"),String)
            End Get
            Set
                Me("qrcode90") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property qrcode91() As String
            Get
                Return CType(Me("qrcode91"),String)
            End Get
            Set
                Me("qrcode91") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property qrcode92() As String
            Get
                Return CType(Me("qrcode92"),String)
            End Get
            Set
                Me("qrcode92") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property qrcode93() As String
            Get
                Return CType(Me("qrcode93"),String)
            End Get
            Set
                Me("qrcode93") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property qrcode94() As String
            Get
                Return CType(Me("qrcode94"),String)
            End Get
            Set
                Me("qrcode94") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property qrcode95() As String
            Get
                Return CType(Me("qrcode95"), String)
            End Get
            Set
                Me("qrcode95") = value
            End Set
        End Property
        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property qrcode96() As String
            Get
                Return CType(Me("qrcode96"), String)
            End Get
            Set
                Me("qrcode96") = Value
            End Set
        End Property



        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property IP() As String
            Get
                Return CType(Me("IP"),String)
            End Get
            Set
                Me("IP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property greenlighttime() As Short
            Get
                Return CType(Me("greenlighttime"),Short)
            End Get
            Set
                Me("greenlighttime") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("1")>
        Public Property redligthtime() As Short
            Get
                Return CType(Me("redligthtime"), Short)
            End Get
            Set
                Me("redligthtime") = value
            End Set
        End Property
        <Global.System.Configuration.UserScopedSettingAttribute(),
        Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
        Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property time_ligh() As String
            Get

                Return CType(Me("time_ligh"), String)
            End Get
            Set
                Me("time_ligh") = Value
            End Set
        End Property
        <Global.System.Configuration.UserScopedSettingAttribute(),
        Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
        Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property delay_time() As String
            Get

                Return CType(Me("delay_time"), String)
            End Get
            Set
                Me("delay_time") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
        Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property Size_8010() As String
            Get

                Return CType(Me("Size_8010"), String)
            End Get
            Set
                Me("Size_8010") = Value
            End Set
        End Property
        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
        Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property Size_8011() As String
            Get

                Return CType(Me("Size_8011"), String)
            End Get
            Set
                Me("Size_8011") = Value
            End Set
        End Property
        <Global.System.Configuration.UserScopedSettingAttribute(),
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property Size_90() As String
            Get

                Return CType(Me("Size_90"), String)
            End Get
            Set
                Me("Size_90") = Value
            End Set
        End Property
        <Global.System.Configuration.UserScopedSettingAttribute(),
        Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
        Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property Size_91() As String
            Get

                Return CType(Me("Size_91"), String)
            End Get
            Set
                Me("Size_91") = Value
            End Set
        End Property
        <Global.System.Configuration.UserScopedSettingAttribute(),
Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property Size_92() As String
            Get

                Return CType(Me("Size_92"), String)
            End Get
            Set
                Me("Size_92") = Value
            End Set
        End Property
        <Global.System.Configuration.UserScopedSettingAttribute(),
Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property Size_93() As String
            Get

                Return CType(Me("Size_93"), String)
            End Get
            Set
                Me("Size_93") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property Size_94() As String
            Get

                Return CType(Me("Size_94"), String)
            End Get
            Set
                Me("Size_94") = Value
            End Set
        End Property
        <Global.System.Configuration.UserScopedSettingAttribute(),
Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property Size_95() As String
            Get

                Return CType(Me("Size_95"), String)
            End Get
            Set
                Me("Size_95") = Value
            End Set
        End Property
        <Global.System.Configuration.UserScopedSettingAttribute(),
Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property Size_96() As String
            Get

                Return CType(Me("Size_96"), String)
            End Get
            Set
                Me("Size_96") = Value
            End Set
        End Property


        <Global.System.Configuration.UserScopedSettingAttribute(),
        Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
        Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property limit() As String
            Get
                Return CType(Me("limit"), String)
            End Get
            Set
                Me("limit") = Value
            End Set
        End Property
    End Class
End Namespace
        
Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.QR014_CODECHECKING.My.MySettings
            Get
                Return Global.QR014_CODECHECKING.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
